#!/bin/bash
#
current=$(gsettings list-recursively | grep 'text-scaling-factor' | awk '{print $NF}')

case $current in
  "1.2")
      gsettings set org.gnome.desktop.interface text-scaling-factor 1.3
    ;;
  "1.3")
      gsettings set org.gnome.desktop.interface text-scaling-factor 1.2
    ;;
  esac


