#!/bin/bash
#
current=$(gsettings list-recursively | grep 'text-scaling-factor' | awk '{print $NF}')

case $current in
  "1.3")
      gsettings set org.gnome.desktop.interface text-scaling-factor 1.4
    ;;
  "1.3999999999999999")
      gsettings set org.gnome.desktop.interface text-scaling-factor 1.3
    ;;
  esac


