#!/bin/bash
#
current=$(gsettings get org.gnome.desktop.interface text-scaling-factor)

case $current in
  "1.3")
      gsettings set org.gnome.desktop.interface text-scaling-factor 1.2
    ;;
  "1.2")
      gsettings set org.gnome.desktop.interface text-scaling-factor 1.3
    ;;
  esac


